{{ if .Values.image.private }}
apiVersion: v1
kind: Secret
metadata:
  name: acr-connection
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}